CREATE SEQUENCE SEQUENCE_EMPRESA START WITH 1 INCREMENT BY 1;

CREATE TABLE empresa (
    id INTEGER PRIMARY KEY,
    razao_social VARCHAR(255) NOT NULL,
    cnpj VARCHAR(255) NOT NULL UNIQUE,
    situacao VARCHAR(50)
);
